audit_header: false
title: "Tampa's Best Real Estate Training - Katrina Madewell"
description: Katrina Madewell, a top Real Estate Agent in Tampa, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: http://tampahometalk.eventbrite.com/
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Katrina Madewell
  title:
  license_number:
  about_markdown: |
    As a full time, well qualified Realtor, Katrina Madewell is experienced to guide you in buying and selling a home in the Tampa, Florida area. This is her chosen career, and SHE LOVES what she does!  Katrina has a mortgage background of more than 18 years!  Throughout the years she has had several hundred clients trust her to consult, negotiate and oversee all the transactional details, it’s what Katrina does best!

    Because your home is your biggest, asset, liability and monthly payment, you can count on Katrina Madewell to deliver the best advise to you and treat your money, like it’s her own!  It’s a responsibility she takes very seriously and your success is her success. So trust, should be your #1 factor when hiring a real estate professional, like Katrina Madewell.
  brand: Tampa Home Talk
  brokerage: Keller Williams Realty
  market: Tampa
  address: 23526 State Road 54 Lutz, FL 33559
  phone: 813-936-2302
  phone_type:
  phone2:
  phone2_type:
  email: KM@tampahometalk.com
  url: http://tampahometalk.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Tampa Home Talk can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: http://facebook.com/tampahometalk
  linkedin_url: http://www.linkedin.com/in/tampahomeskatrina
  youtube_url: http://www.youtube.com/kmadewel
  twitter_url: http://twitter.com/tampahometalk
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Tampa Real Estate Podcast with Katrina Madewell'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Tampa Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Tampa Home Talk - your professional Tampa Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Tampa, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Katrina Madewell'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Tampa Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#8A3F94'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#8A3F94'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
